name: kubectx 
version: '0.5.0'
summary: A tool to switch between Kubernetes contexts 
description: |
    Fast way to switch between clusters and namespaces in kubectl!

grade: devel 
confinement: classic 

apps:
    kubectx:
        command: bash $SNAP/kubectx
    kubens:
        command: bash $SNAP/kubens

parts:
    kubectx:
        plugin: dump 
        source: git@github.com:ahmetb/kubectx.git 
